#!/bin/bash
i_______icounter=0;
while [ 1 ]
do
	. /tmp/input.$i_______icounter >> /tmp/output 2 >> /tmp/output
	i_______icounter=$((i_______icounter+1))
	test -f /tmp/input.$i_______icounter
	val=$?
	while [ $val -ne 0 ]
	do
		test -f /tmp/input.$i_______icounter
		val=$?
		#		read -p "" -t 0.1
		sleep 0.5
	done
done
